import type { Metadata } from 'next';
import Link from 'next/link';
import { Search, Calculator, PackageCheck, ShieldCheck, Video, Truck } from 'lucide-react';
import styles from '../sell-on-amazon/AmazonGuide.module.css';
import guide from './TikTokGuide.module.css';

const title='Source in China. Sell on TikTok Shop.';
const description='A practical UK and US TikTok Shop selling guide: product ideas, sourcing, branding, creator partnerships, delivery and estimated profit.';
export const metadata:Metadata={title:`${title} | LineScout by Sure Imports`,description,alternates:{canonical:'https://linescout.sureimports.com/sell-on-tiktok-shop'},openGraph:{title,description,url:'https://linescout.sureimports.com/sell-on-tiktok-shop'},twitter:{card:'summary',title,description}};
const sources={
  ukRegistration:'https://seller-uk.tiktok.com/university/essay?knowledge_id=10005795&lang=en-GB',
  usRegistration:'https://seller-us.tiktok.com/university/course?content_id=6837894379964161&lang=en&learning_id=6033035939809038',
  ukFees:'https://seller-uk.tiktok.com/university/essay?knowledge_id=7753824408913665&lang=en-GB',
  usFees:'https://seller-us.tiktok.com/university/essay?knowledge_id=5988482086864682',
  samples:'https://seller-uk.tiktok.com/university/essay?default_language=en-GB&knowledge_id=2490998925051680',
  restricted:'https://seller-us.tiktok.com/university/essay?default_language=en&knowledge_id=3238037484275457',
  content:'https://seller-us.tiktok.com/university/essay?knowledge_id=6837891779151617',
  ukDelivery:'https://seller-uk.tiktok.com/university/essay?default_language=en-GB&knowledge_id=7030563657811734',
  usDelivery:'https://seller-us.tiktok.com/university/essay?knowledge_id=3995852763301633',
};
const steps=[
  {icon:Search,title:'Choose a product people can understand quickly.',body:'Look for a clear use, an easy demonstration and a reason to buy. Compare similar offers, customer complaints, selling prices and the size and weight of the package. Use LineScout’s researched product ideas and estimated landed costs as a starting point, not proof that something will sell.',check:'Try this: explain the benefit in one sentence and show it with a real sample. Views and likes are not the same as paid orders.'},
  {icon:ShieldCheck,title:'Check your shop and product eligibility first.',body:'Choose the UK or US registration route that genuinely matches your circumstances. Check account requirements, permitted categories and the evidence needed for your product. Some restricted categories need approval. Branding does not remove safety, intellectual-property or labelling responsibilities.',check:'Before buying stock: confirm the requirements in your market’s Seller Center. A registered company alone does not guarantee account or product approval.',href:sources.restricted,link:'TikTok Shop US restricted-product guidance'},
  {icon:Calculator,title:'Check what you could earn on each sale.',body:'Include the product, import shipping, delivery to the buyer, platform fees, creator commissions and advertising. Allow for samples, returns and overhead. If you offer a discount or free delivery, work out who pays for it. Avoid counting a cost twice if it is already in your landed estimate.',check:'Before ordering: use the calculator, then test a lower selling price and higher marketing costs. Keep money available for refunds and the next order.'},
  {icon:PackageCheck,title:'Source a sample before a bulk order.',body:'Send your product brief through LineScout. Discuss supplier options, quantities, branding, packaging and shipping with Sure Imports. Approve the sample and written specification, and agree inspection scope and any required documents before production.',check:'Before paying: confirm the quoted services, delivery destination and what is not included. A good sample is not a guarantee that every production unit will match.'},
  {icon:Video,title:'Build an accurate listing and a content plan.',body:'Show the actual product, size, materials and what comes in the package. Make short demonstrations that answer a buyer’s questions. You can create your own content and explore creator collaborations. Keep claims, prices and demonstrations consistent with the product and listing.',check:'Before publishing: avoid misleading results, unsupported claims and offers with hidden conditions. Follow the current content and advertising disclosure requirements.',href:sources.content,link:'TikTok Shop content policy'},
  {icon:Truck,title:'Have stock and delivery ready before launch.',body:'Agree where stock will be held, how orders will be packed and dispatched, and where returns will go. Importing stock from China and delivering a TikTok order to a buyer are separate jobs. Use the fulfilment options available to your shop and meet the applicable dispatch and delivery deadlines.',check:'Before taking orders: test your stock, tracking and returns workflow. Do not promise delivery dates that your supply chain cannot meet.',href:sources.usDelivery,link:'TikTok Shop US fulfilment policy'},
];
const markets=[
  {code:'GB',id:'uk',flag:'🇬🇧',name:'United Kingdom',currency:'GBP',body:'Use the UK Seller Center to check the current individual or business registration requirements. Prepare the identity, business, address and payout information requested for your route. Work out your UK stock, customer delivery and returns arrangements.',registration:sources.ukRegistration,fees:sources.ukFees,delivery:sources.ukDelivery},
  {code:'US',id:'us',flag:'🇺🇸',name:'United States',currency:'USD',body:'Check the US registration route for your circumstances, including the identity, residency or business, tax and bank information it requires. UK approval does not give you US approval. Confirm product eligibility and a delivery arrangement that meets the US shop’s requirements.',registration:sources.usRegistration,fees:sources.usFees,delivery:sources.usDelivery},
];

export default function TikTokGuide(){return <main className={styles.page}>
  <header className={styles.hero}><span className={styles.eyebrow}>THE CHINA-TO-TIKTOK SHOP GUIDE</span><h1>Source in China.<br/>Sell on TikTok Shop.</h1><p>Find a product, put your brand on it and plan how to sell it. A practical starting point for TikTok Shop sellers in the UK and US.</p><div className={styles.actions}><Link className={styles.primary} href="/white-label">Explore product ideas</Link><Link className={styles.secondary} href="/amazon-profit-calculator?platform=tiktok">Calculate estimated profit</Link></div><nav className={styles.marketLinks} aria-label="Choose your TikTok Shop market">{markets.map(m=><a key={m.id} href={'#market-'+m.id}><span aria-hidden="true">{m.flag}</span>{m.name}</a>)}</nav><small>Independent guidance from LineScout and Sure Imports. Not affiliated with TikTok Shop.</small></header>
  <div className={styles.container}>
    <section className={styles.intro}><div><span className={styles.eyebrow}>A PRODUCT PEOPLE CAN SEE IN ACTION</span><h2>Your brand.<br/>A clear reason to buy.</h2></div><div><p>TikTok Shop connects product discovery with shopping through content. Your job is more than finding cheap stock: you need a useful product, an honest demonstration, reliable delivery and enough profit left after the costs.</p><p>White labelling means selling a manufacturer’s existing product under your own brand, where permitted. LineScout helps you explore researched ideas and estimated landed costs. Sure Imports helps with the sourcing and shipping agreed in your quotation. You own the shop and the customer relationship.</p></div></section>
    <section className={styles.section} id="the-process"><span className={styles.eyebrow}>FROM IDEA TO FIRST ORDERS</span><h2>Six steps before you scale.</h2><p className={styles.lead}>Start with a product you understand and a budget you can control. A viral video is not a business plan.</p><div className={styles.steps}>{steps.map((s,i)=><article key={s.title}><div className={styles.stepTop}><s.icon size={24} aria-hidden="true"/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.body}</p><p className={styles.check}>{s.check}</p>{s.href&&<a className={guide.sourceLink} href={s.href} target="_blank" rel="noopener noreferrer">{s.link}</a>}</article>)}</div></section>
    <section className={styles.economics} id="profit"><div><span className={styles.eyebrow}>SALES ARE NOT THE SAME AS PROFIT</span><h2>A £25 sale.<br/>What do you keep?</h2><p>Include what you spend to get the sale, not just what you paid the supplier. Creator commission and advertising are separate costs.</p><Link className={styles.primary} href="/amazon-profit-calculator?platform=tiktok&market=GB">Check your estimated profit</Link></div><div className={styles.costs}><h3>Illustrative profit per product</h3><dl>{[
      ['Selling price','£25.00'],['Product + import costs','− £8.00'],['Delivery to buyer','− £3.00'],['Platform fee','− £2.25'],['Creator commission, averaged','− £1.25'],['Advertising','− £2.00'],['Samples + content allowance','− £0.50'],['Returns allowance','− £0.50'],['Allocated monthly overhead','− £1.00'],['Estimated profit before income tax','£6.50'],
    ].map(([label,amount])=><div key={label}><dt>{label}</dt><dd>{amount}</dd></div>)}</dl><p>Example only, not a current fee quotation or promise of earnings. It assumes a 9% platform fee, 10% creator commission on half of sales, and £100 overhead across 100 products. No additional included sales tax is assumed. Your fees and tax position may differ; enter your own figures.</p></div></section>
    <section className={styles.section} id="creators"><span className={styles.eyebrow}>CREATORS, WITHOUT GUESSWORK</span><h2>Pay attention to fit, cost and results.</h2><div className={styles.markets}>{[
      ['Choose relevant creators','Look for an audience and content style that fit the product. Start with a small, manageable group. A large follower count does not guarantee orders.'],
      ['Agree the offer','Set a commission you can afford. Budget for samples and sample delivery. Clarify deliverables and any permission to reuse content in advertising; do not assume receiving a video gives you unrestricted rights.'],
      ['Measure what you keep','Compare settled sales with commissions, ad spend, sample costs and refunds. Expand the collaborations that produce useful results, not just views.'],
    ].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><a className={guide.sourceLink} href={sources.samples} target="_blank" rel="noopener noreferrer">Read TikTok Shop UK’s sample guidance</a></section>
    <section className={styles.section} id="markets"><span className={styles.eyebrow}>CHOOSE YOUR MARKET</span><h2>Start with the right requirements.</h2><p className={styles.lead}>This guide covers the UK and US. Check the official registration route before paying for inventory. Seller, creator and cross-border programmes can have different requirements.</p><div className={`${styles.markets} ${guide.twoColumns}`}>{markets.map(m=><article id={'market-'+m.id} key={m.id}><span className={styles.flag} aria-hidden="true">{m.flag}</span><h3>{m.name}</h3><strong>TikTok Shop · {m.currency}</strong><p>{m.body}</p><a href={m.registration} target="_blank" rel="noopener noreferrer">Registration requirements</a><a href={m.fees} target="_blank" rel="noopener noreferrer">Current platform fees</a><a href={m.delivery} target="_blank" rel="noopener noreferrer">Delivery and fulfilment guidance</a><Link href={'/amazon-profit-calculator?platform=tiktok&market='+m.code}>Calculate profit in {m.currency}</Link></article>)}</div><p className={styles.note}>Policies and fees change. Follow the guidance for your account and product in Seller Center. This is general education, not legal or tax advice; get qualified advice for your circumstances.</p></section>
    <section className={styles.section}><span className={styles.eyebrow}>YOUR FIRST CONTENT PLAN</span><h2>Answer the questions buyers actually ask.</h2><div className={styles.steps}>{[
      ['Show the use','Demonstrate the product doing its actual job. Show the starting situation, the product in use and the result without misleading edits.'],
      ['Show the details','Explain the size, materials, variants and what is included. A buyer should not need to guess from a polished photograph.'],
      ['Answer an objection','Show how to clean, store or use it. Explain limitations honestly. Use real questions from comments and customer enquiries.'],
      ['Learn from completed orders','Track purchases, cancellations, refunds and profit. Improve one thing at a time rather than increasing spend because a video received attention.'],
    ].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={styles.section}><span className={styles.eyebrow}>KNOW WHO DOES WHAT</span><h2>Sourcing support. Your selling business.</h2><div className={styles.markets}>{[
      ['LineScout','Research product ideas and estimated landed costs, calculate potential profit, and prepare your sourcing brief. Ideas are starting points, not guaranteed opportunities.'],
      ['Sure Imports','Discuss suppliers, samples, branding, inspection and shipping. The quotation defines the services and delivery destination. Daily TikTok customer-order fulfilment is not automatically included.'],
      ['You, the seller','Run your shop, verify eligibility and compliance, manage listings and creators, arrange customer delivery, handle support and returns, and track cash flow.'],
    ].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={styles.section}><span className={styles.eyebrow}>BEFORE YOU START</span><h2>Common questions, plain answers.</h2><div className={styles.faq}>{[
      ['Do I need a large following?','Do not confuse seller registration with creator eligibility. Check the requirements for the role and market you are applying for. You can plan your own content and creator collaborations, but neither guarantees sales.'],
      ['Can I put my own brand on a product?','Often, where the supplier allows it and you have the right to use the branding. Confirm minimum quantities, packaging costs and samples. Branding does not guarantee exclusivity or platform approval.'],
      ['Can you ship each TikTok order directly from China?','Do not assume this is part of your sourcing order. Agree where stock will be delivered and how customer orders will be fulfilled before launch. Your arrangements must meet TikTok Shop’s applicable deadlines and policies.'],
      ['Are creator samples free for me?','No. Even if the creator receives a free sample, you still fund the product and its delivery. Include those costs when estimating profit. A sample is not a guarantee of content or sales.'],
      ['Do you open or manage my TikTok Shop?','The sourcing service does not automatically include shop registration, listing management, creator management or daily order fulfilment. Any additional service must be agreed separately.'],
      ['How much should I order first?','Choose a quantity based on your budget, supplier minimum, fulfilment capacity and evidence of demand. Leave money for marketing, returns and reorders. There is no universal safe order quantity.'],
    ].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className={styles.closing}><span className={styles.eyebrow}>START WITH A PRODUCT AND A PLAN</span><h2>Find an idea. Check the numbers.</h2><p>Then tell us what you want to source, brand and ship.</p><div className={styles.actions}><Link className={styles.primary} href="/white-label">Explore product ideas</Link><Link className={styles.secondary} href="/white-label/start">Build your sourcing brief</Link></div><Link className={guide.sourceLink} href="/sell-on-amazon">Considering Amazon too? Read the Amazon selling guide</Link></section>
  </div>
</main>;}
