'use client';
import CalculationSave from '@/components/calculations/CalculationSave';
import {CALCULATION_VERSION,type CalculationRecord} from '@/lib/calculation-records';
import { useState } from 'react';
import SearchableSelect from '@/app/internal/_components/SearchableSelect';
import { Calculator as CalculatorIcon, RotateCcw, Info } from 'lucide-react';
import { MARKETS, blankDraft, parseDraft, evaluate, priceForMargin, type Market, type Draft, type NumericKey } from '@/lib/amazon-calculator';
import styles from './Calculator.module.css';

const labels:Record<NumericKey,string>={price:'Selling price per product',landed:'Product cost, including import and shipping',product:'Product + branding per unit',freight:'Freight per unit',importCosts:'Import costs per unit',prep:'Additional preparation per unit',fulfilment:'Delivery / fulfilment fee per product',storage:'Storage allowance per unit',other:'Other selling costs per unit',referral:'Referral fee (%)',minimumReferral:'Minimum referral fee per unit',feeTax:'Unrecoverable tax on Amazon fees (%)',advertising:'Advertising allowance (% of price)',returns:'Returns allowance (% of price)',outputTax:'Tax included in selling price (%)',targetMargin:'Target profit margin (%)',units:'Units sold per month',overhead:'Monthly business overhead'};
export default function Calculator({initialMarket,product,low,high,initialRecord}:{initialMarket:Market;product:string;low:number|null;high:number|null;initialRecord?:CalculationRecord}){
  const [market,setMarket]=useState<Market>(initialMarket);
  const [draft,setDraft]=useState<Draft>(()=>initialRecord?initialRecord.draft as Draft:({...blankDraft(),landed:high!==null?String(high):low!==null?String(low):''}));
  const [name,setName]=useState(initialRecord?.name||product);const [notice,setNotice]=useState('');const [sourceVisible,setSourceVisible]=useState(!!product);const [ack,setAck]=useState(false);
  const [touched,setTouched]=useState<Partial<Record<NumericKey,boolean>>>({});
  const parsed=parseDraft(draft),v=parsed.values,r=v?evaluate(v):null;
  const m=MARKETS[market],money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:m.currency,maximumFractionDigits:2}).format(n);
  const set=(key:NumericKey,value:string)=>{setDraft(d=>({...d,[key]:value}));setAck(false);};
  function field(key:NumericKey,help?:string){const error=touched[key]?parsed.errors[key]:undefined;return <label className={styles.field} key={key} htmlFor={key}><span>{labels[key]}{!['referral','feeTax','advertising','returns','outputTax','targetMargin','units'].includes(key)&&` (${m.currency})`}</span><input id={key} type="number" inputMode="decimal" min="0" step={key==='units'?'1':'any'} value={draft[key]} onInput={e=>set(key,e.currentTarget.value)} onChange={e=>set(key,e.target.value)} onBlur={()=>setTouched(t=>({...t,[key]:true}))} aria-invalid={!!error} aria-describedby={help||error?key+'-help':undefined}/>{(help||error)&&<small id={key+'-help'} className={error?styles.error:undefined}>{error||help}</small>}</label>;}
  function reset(nextMarket=market){setMarket(nextMarket);setDraft(blankDraft());setTouched({});setAck(false);setSourceVisible(false);setName('');setNotice(nextMarket===market?'Calculation cleared.':'Currency changed. Amounts have been cleared; no currency conversion was applied.');}
  function sample(){setSourceVisible(false);setName('Illustrative example');setDraft({...blankDraft(),price:'25',landed:'9',fulfilment:'3.25',referral:'15',advertising:'12',returns:'4',storage:'0',targetMargin:'20'});setAck(false);setTouched({});setNotice('Illustrative inputs loaded in '+m.currency+'. These are not current Amazon fees. Replace them with your own costs.');}
  const breakdown=r&&v?[['Landed product cost',r.landed],['Preparation',v.prep],['Referral fee',r.referral],['Fulfilment',v.fulfilment],['Storage',v.storage],['Unrecoverable fee tax',r.feeTax],['Advertising allowance',r.advertising],['Returns allowance',r.returns],['Other selling costs',v.other]] as const:[];
  return <div className={styles.page}>
    <div className={styles.container}>
      <div className={styles.marketRow} aria-label="Marketplace">{(Object.keys(MARKETS) as Market[]).map(k=><button key={k} type="button" aria-pressed={market===k} onClick={()=>{if(k!==market)reset(k);}}><span aria-hidden="true">{MARKETS[k].flag}</span><strong>{MARKETS[k].name}</strong><small>{MARKETS[k].currency}</small></button>)}</div>
      <p className={styles.note}>All amounts use {m.currency}. Changing market clears amounts, not converts them. Amazon UK, Canada and US. Optional costs start at zero; include any that apply.</p>
      <div className={styles.toolbar}><label>Name (optional, for saving)<input maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="For example, branded storage bags"/></label><div className={styles.actions}><button type="button" onClick={sample}>Try an example</button><button type="button" onClick={()=>reset()}><RotateCcw size={16}/>Reset</button></div></div>
      {sourceVisible&&<div className={styles.source}><Info size={20}/><div><strong>{product}</strong><p>{low!==null||high!==null?`Catalogue estimate: ${low!==null?money(low):'—'}${high!==null?' to '+money(high):''} per unit. We prefilled the upper estimate where available. Confirm the quotation, quantity and included costs before relying on it.`:'No cost estimate was supplied. Enter your quotation or estimate below.'}</p><small>This is an editable planning estimate passed from the catalogue, not a verified quote. No currency conversion has been performed.</small></div></div>}
      {notice&&<p role="status" className={styles.notice}>{notice}</p>}
      <div className={styles.workspace}><div className={styles.inputs}>
        <section className={styles.panel}><div className={styles.sectionTitle}><span>01</span><h2>Enter the essentials</h2></div><p>Start with these five figures. Use your own costs, or try the example above.</p><div className={styles.fields}>
          {field('price','What the buyer pays per product, including any delivery charge you receive. Exclude tax collected separately by Amazon.')}
          {draft.costMode==='landed'?field('landed','Your cost to buy and import one product, including branding, freight and import charges.'): <div className={styles.field}><span>Itemised product costs are enabled</span><small>Edit the product, freight and import amounts in More options below.</small></div>}
          {field('referral','Copy your product’s referral fee from Amazon. This percentage is not the same for every category.')}
          {field('fulfilment','Amazon FBA or your own delivery cost for one product, not the import shipping already included above.')}
          {field('advertising','Your planned ad spend as a share of sales. Leave 0 if you will not run ads.')}
        </div><p className={styles.note}><a href={m.calculator} target="_blank" rel="noopener noreferrer">Find your fees in Amazon’s calculator</a>. No live fees are retrieved here.</p></section>
        <details className={styles.panel}><summary className={styles.optionsSummary}>More options <span>Tax, packing, storage, returns and monthly costs{['outputTax','prep','minimumReferral','storage','feeTax','returns','other','overhead'].some(k=>Number(draft[k as NumericKey])>0)?' · adjustments included':''}</span></summary><div className={styles.advancedFields}>
          <fieldset className={styles.segment}><legend>How would you like to enter product costs?</legend>{(['landed','itemised'] as const).map(mode=><label key={mode}><input type="radio" name="costMode" checked={draft.costMode===mode} onChange={()=>{setDraft(d=>({...d,costMode:mode}));setAck(false);}}/>{mode==='landed'?'One total cost':'Enter the cost breakdown'}</label>)}</fieldset>
          <div className={styles.fields}>{draft.costMode==='itemised'&&<>{field('product')}{field('freight')}{field('importCosts','Only non-recoverable import costs not already entered elsewhere.')}</>}{field('outputTax','Only tax already included in your selling price and payable by you. Leave 0 if none. This is not tax advice.')}{field('prep','Extra packing or labels not included in product cost.')}{field('minimumReferral','Use 0 unless your category has a minimum fee.')}<div className={styles.field}><span id="fee-basis-label">Referral percentage applies to</span><div className={styles.picker} role="group" aria-labelledby="fee-basis-label"><SearchableSelect value={draft.feeBasis} variant="light" options={[{value:"gross",label:"Full entered selling price"},{value:"net",label:"Selling price excluding included tax"}]} onChange={value=>{setDraft(d=>({...d,feeBasis:value as Draft["feeBasis"]}));setAck(false);}} /></div><small>Choose the basis that matches your marketplace/category fee calculation.</small></div></div>
          <fieldset className={styles.segment}><legend>Fulfilment method</legend>{(['fba','self'] as const).map(mode=><label key={mode}><input type="radio" name="fulfilment" checked={draft.fulfilmentMode===mode} onChange={()=>{setDraft(d=>({...d,fulfilmentMode:mode,fulfilment:'',storage:'0'}));setAck(false);}}/>{mode==='fba'?'Amazon FBA':'I arrange delivery'}</label>)}</fieldset>
          <div className={styles.fields}>{field('storage','Storage for the expected holding period, allocated per product.')}{field('feeTax','Extra unrecoverable tax on referral, FBA and storage fees. Leave 0 if already included or recoverable.')}{field('returns','Average return-related losses and costs as a share of sales, not the percentage of orders returned.')}{field('other','Per-product costs not already included above.')}{field('targetMargin','Desired profit as a percentage of revenue after included tax, including allocated monthly overhead.')}{field('units','Used to estimate monthly profit and spread monthly overhead across products. Not a sales forecast.')}{field('overhead','Fixed monthly expenses. We divide these by expected units to include them in profit per product.')}</div>
        </div></details>
        <label className={styles.confirm}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>I have checked my costs and fees. I understand this is an estimate.</span></label>
      </div><aside className={styles.results} aria-label="Calculation results">
        {!r||!v?<section className={styles.panel}><CalculatorIcon size={28}/><h2>Start with your actual costs.</h2><p>Complete the fields below to see a useful estimate. Zero is allowed where a cost does not apply.</p><ul>{Object.entries(parsed.errors).map(([key])=><li key={key}><a href={'#'+key} onClick={()=>{const panel=document.getElementById(key)?.closest('details');if(panel)panel.open=true;}}>{labels[key as NumericKey]}</a></li>)}</ul><button type="button" onClick={sample}>Try an illustrative example</button></section>:<>
          <section className={styles.resultHero}><span className={styles.kicker}>{ack?'YOUR PLANNING ESTIMATE':'DRAFT · CONFIRM YOUR ASSUMPTIONS'}</span><h2>Estimated profit per product</h2><strong className={r.profit<0?styles.loss:undefined}>{money(r.profit)}</strong><p>{r.profitMargin.toFixed(1)}% estimated profit margin · before income tax</p>{r.profit<=0&&<p className={styles.warning}>At this price, the entered costs leave no estimated profit. Revisit the price, costs or product.</p>}<dl><div><dt>Break-even selling price</dt><dd>{priceForMargin({...v,other:v.other+v.overhead/v.units})===null?'Not achievable':money(priceForMargin({...v,other:v.other+v.overhead/v.units})!)}</dd></div><div><dt>Price for {v.targetMargin}% margin</dt><dd>{priceForMargin({...v,other:v.other+v.overhead/v.units},v.targetMargin)===null?'Not achievable':money(priceForMargin({...v,other:v.other+v.overhead/v.units},v.targetMargin)!)}</dd></div><div><dt>Monthly profit at {v.units} sales</dt><dd>{money(r.monthly)}</dd></div><div><dt>Inventory + prep for {v.units} units</dt><dd>{money(r.inventoryCash)}</dd></div></dl><small>After the costs you entered, including allocated monthly overhead. Before income tax. Add any extra costs and change expected monthly sales in More options.</small></section>
          <section className={styles.panel}><h2>Where the money goes</h2><dl className={styles.breakdown}><div><dt>Selling price</dt><dd>{money(v.price)}</dd></div><div><dt>Included tax removed</dt><dd>{money(r.tax)}</dd></div><div><dt>Net sales revenue</dt><dd>{money(r.revenue)}</dd></div>{breakdown.filter(([,amount])=>amount!==0).map(([label,amount])=><div key={label}><dt>{label}</dt><dd>{money(amount)}</dd></div>)}<div><dt>Monthly overhead per product</dt><dd>{money(v.overhead/v.units)}</dd></div><div><dt>Estimated profit</dt><dd>{money(r.profit)}</dd></div></dl><p>Maximum blended ad spend before unit break-even: {(r.profit+r.advertising)<0?'none; other costs already exceed revenue':((r.profit+r.advertising)/v.price*100).toFixed(1)+'% of selling price'}. Includes allocated monthly overhead.</p></section>
          <section className={styles.panel}><h2>What if things change?</h2><p>Each scenario changes one assumption. Nothing here predicts sales.</p><div className={styles.scenarios}>{[
            ['Selling price falls 10%',evaluate({...v,price:v.price*.9})],
            ['Product landed cost rises 10%',evaluate({...v,costMode:'landed',landed:r.landed*1.1})],
            ['Ads take 5 percentage points more',evaluate({...v,advertising:Math.min(100,v.advertising+5)})],
          ].map(([label,result])=><div key={String(label)}><span>{String(label)}</span><strong>{money((result as ReturnType<typeof evaluate>).profit)}</strong><small>estimated profit per product</small></div>)}</div></section>
        </>}
      <div hidden={!v||!r}><CalculationSave input={{name,platform:'amazon',market,draft,modelVersion:CALCULATION_VERSION}} confirmed={ack} initialRecord={initialRecord}/></div></aside></div>
      <section className={styles.method}><h2>Understand what this estimate can—and cannot—tell you.</h2><p>Estimated profit per product = sales revenue after included tax − all entered per-product costs − monthly overhead divided by expected units sold. Estimated monthly profit = profit per product × expected units sold. These are estimates before income tax, not guaranteed earnings.</p><p>Fee percentages, minimum fees and fulfilment costs are your inputs. This model does not automatically account for tiered category rates, promotional fees, size changes, exchange rates, VAT registration, tax recovery, refunds or Amazon policy changes. Revalidate those before placing an order. A positive estimate is not proof of demand, product eligibility or profitability.</p><a href={m.fees} target="_blank" rel="noopener noreferrer">Check Amazon’s current {m.name} fee guidance</a><p>Independent guidance from LineScout and Sure Imports. Not affiliated with Amazon. No selling credentials or payments are needed to use this calculator.</p></section>
    </div>
  </div>;
}
