CREATE TABLE IF NOT EXISTS linescout_white_label_seo_batches (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_key VARCHAR(80) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
  target_size SMALLINT NOT NULL DEFAULT 25,
  selection_method VARCHAR(120) NOT NULL DEFAULT 'gsc_then_views',
  scheduled_for DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_wl_seo_batch_key (batch_key),
  KEY idx_wl_seo_batch_status_schedule (status, scheduled_for)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS linescout_white_label_seo_batch_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  position SMALLINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  priority_score DECIMAL(12,4) NOT NULL DEFAULT 0,
  priority_reason VARCHAR(500) NULL,
  view_count_snapshot INT NOT NULL DEFAULT 0,
  gsc_clicks_snapshot INT NOT NULL DEFAULT 0,
  gsc_impressions_snapshot INT NOT NULL DEFAULT 0,
  gsc_position_snapshot DECIMAL(10,4) NULL,
  primary_query VARCHAR(700) NULL,
  supporting_queries_json JSON NULL,
  search_intent VARCHAR(40) NULL,
  authoring_brief_json JSON NULL,
  validation_json JSON NULL,
  content_revision_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_wl_seo_batch_product (batch_id, product_id),
  KEY idx_wl_seo_batch_item_status (status, batch_id),
  KEY idx_wl_seo_batch_item_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS linescout_white_label_seo_revisions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  product_id BIGINT NOT NULL,
  slug VARCHAR(255) NOT NULL,
  version INT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  content_json JSON NOT NULL,
  primary_keyword VARCHAR(255) NULL,
  supporting_keywords_json JSON NULL,
  search_intent VARCHAR(40) NULL,
  source_queries_json JSON NULL,
  source_content_checksum CHAR(64) NULL,
  quality_score DECIMAL(5,2) NULL,
  validation_json JSON NULL,
  batch_id BIGINT NULL,
  created_by VARCHAR(120) NULL,
  reviewed_by VARCHAR(120) NULL,
  reviewed_at DATETIME NULL,
  published_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_wl_seo_product_version (product_id, version),
  KEY idx_wl_seo_revision_public (product_id, status, version),
  KEY idx_wl_seo_revision_slug (slug, status, version),
  KEY idx_wl_seo_revision_batch (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

