import type { PoolConnection } from "mysql2/promise";
import fs from "fs";
import path from "path";

export type WhiteLabelProductSeed = {
  product_name: string;
  category: string;
  short_desc: string | null;
  why_sells: string | null;
  regulatory_note: string | null;
  mockup_prompt: string | null;
  image_url: string | null;
  slug?: string | null;
  seo_title?: string | null;
  seo_description?: string | null;
  business_summary?: string | null;
  market_notes?: string | null;
  white_label_angle?: string | null;
  fob_low_usd: number | null;
  fob_high_usd: number | null;
  cbm_per_1000: number | null;
  sort_order: number;
  is_active: 0 | 1;
};

export const WHITE_LABEL_PRICING_DEFAULTS = {
  fx_rate_ngn: 1500,
  cbm_rate_ngn: 450000,
  markup_percent: 0.2,
} as const;

export const WHITE_LABEL_PRODUCT_SEED: WhiteLabelProductSeed[] = [

  {
    product_name: 'USB-C braided cables',
    category: 'Phone & Computer Accessories',
    short_desc: 'Spare cables are a daily need for phones and power banks.',
    why_sells: 'Spare cables are a daily need for phones and power banks.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Braided USB-C cable with minimal packaging, brand name YOUR LOGO on sleeve.',
    image_url: null,
    fob_low_usd: 0.9,
    fob_high_usd: 2.5,
    cbm_per_1000: 0.5,
    sort_order: 1,
    is_active: 1,
  },
  {
    product_name: 'USB-C wall chargers (18–30W)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Fast charging demand is strong across Android devices.',
    why_sells: 'Fast charging demand is strong across Android devices.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Compact 20–30W USB-C wall charger, white matte, YOUR LOGO printed.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.5,
    sort_order: 2,
    is_active: 1,
  },
  {
    product_name: 'Car chargers (dual-port)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Ride-hailing drivers need multi-device charging.',
    why_sells: 'Ride-hailing drivers need multi-device charging.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Dual-port car charger in black, YOUR LOGO on the side.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.5,
    sort_order: 3,
    is_active: 1,
  },
  {
    product_name: 'Power banks (10,000mAh)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Power outages make power banks essential.',
    why_sells: 'Power outages make power banks essential.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Slim 10,000mAh power bank, YOUR LOGO center, retail box.',
    image_url: null,
    fob_low_usd: 5.0,
    fob_high_usd: 9.0,
    cbm_per_1000: 1.0,
    sort_order: 4,
    is_active: 1,
  },
  {
    product_name: 'Tempered glass screen protectors',
    category: 'Phone & Computer Accessories',
    short_desc: 'High replacement rate and low cost impulse buy.',
    why_sells: 'High replacement rate and low cost impulse buy.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Tempered glass protector with clean box, YOUR LOGO.',
    image_url: null,
    fob_low_usd: 0.5,
    fob_high_usd: 1.8,
    cbm_per_1000: 0.5,
    sort_order: 5,
    is_active: 1,
  },
  {
    product_name: 'Phone cases (TPU)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Phone case replacement cycle is frequent.',
    why_sells: 'Phone case replacement cycle is frequent.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Clear TPU case with subtle YOUR LOGO branding on packaging.',
    image_url: null,
    fob_low_usd: 0.6,
    fob_high_usd: 1.2,
    cbm_per_1000: 0.5,
    sort_order: 6,
    is_active: 1,
  },
  {
    product_name: 'Laptop sleeves',
    category: 'Phone & Computer Accessories',
    short_desc: 'Students and remote workers need protection on the go.',
    why_sells: 'Students and remote workers need protection on the go.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: '13–15 inch laptop sleeve, minimalist, YOUR LOGO stitched.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.0,
    sort_order: 7,
    is_active: 1,
  },
  {
    product_name: 'Aluminum laptop stands',
    category: 'Phone & Computer Accessories',
    short_desc: 'Affordable premium desk upgrade.',
    why_sells: 'Affordable premium desk upgrade.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Adjustable aluminum laptop stand, YOUR LOGO etched.',
    image_url: null,
    fob_low_usd: 8.0,
    fob_high_usd: 15.0,
    cbm_per_1000: 1.0,
    sort_order: 8,
    is_active: 1,
  },
  {
    product_name: 'Wireless mouse',
    category: 'Phone & Computer Accessories',
    short_desc: 'Every laptop user needs a mouse.',
    why_sells: 'Every laptop user needs a mouse.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Silent-click wireless mouse, YOUR LOGO on top.',
    image_url: null,
    fob_low_usd: 8.0,
    fob_high_usd: 15.0,
    cbm_per_1000: 0.5,
    sort_order: 9,
    is_active: 1,
  },
  {
    product_name: 'Keyboard + mouse combo',
    category: 'Phone & Computer Accessories',
    short_desc: 'Home office and study setups are growing.',
    why_sells: 'Home office and study setups are growing.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Wireless keyboard + mouse set, YOUR LOGO on box.',
    image_url: null,
    fob_low_usd: 8.0,
    fob_high_usd: 15.0,
    cbm_per_1000: 1.0,
    sort_order: 10,
    is_active: 1,
  },
  {
    product_name: 'USB-C hubs (basic)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Laptops with few ports need hubs.',
    why_sells: 'Laptops with few ports need hubs.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: '6-in-1 USB-C hub, YOUR LOGO on aluminum shell.',
    image_url: null,
    fob_low_usd: 6.5,
    fob_high_usd: 14.5,
    cbm_per_1000: 0.5,
    sort_order: 11,
    is_active: 1,
  },
  {
    product_name: 'Bluetooth earbuds (basic)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Always-on demand for affordable audio.',
    why_sells: 'Always-on demand for affordable audio.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Budget earbuds in small case, YOUR LOGO on lid.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 5.0,
    cbm_per_1000: 0.5,
    sort_order: 12,
    is_active: 1,
  },
  {
    product_name: 'Cable organizers / tech pouches',
    category: 'Phone & Computer Accessories',
    short_desc: 'Easy add-on with good perceived value.',
    why_sells: 'Easy add-on with good perceived value.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Compact tech pouch, YOUR LOGO on patch.',
    image_url: null,
    fob_low_usd: 1.5,
    fob_high_usd: 3.0,
    cbm_per_1000: 0.5,
    sort_order: 13,
    is_active: 1,
  },
  {
    product_name: 'Phone stands',
    category: 'Phone & Computer Accessories',
    short_desc: 'Cheap accessory for desks and video calls.',
    why_sells: 'Cheap accessory for desks and video calls.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Foldable phone stand, YOUR LOGO on base.',
    image_url: null,
    fob_low_usd: 0.8,
    fob_high_usd: 1.5,
    cbm_per_1000: 0.5,
    sort_order: 14,
    is_active: 1,
  },
  {
    product_name: 'Webcam covers + privacy filters',
    category: 'Phone & Computer Accessories',
    short_desc: 'Remote work privacy add-on.',
    why_sells: 'Remote work privacy add-on.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Webcam cover set with YOUR LOGO on card.',
    image_url: null,
    fob_low_usd: 0.5,
    fob_high_usd: 1.0,
    cbm_per_1000: 0.5,
    sort_order: 15,
    is_active: 1,
  },
  {
    product_name: 'Smart plugs',
    category: 'Tech / Smart Utility',
    short_desc: 'Low-cost smart home starter.',
    why_sells: 'Low-cost smart home starter.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Wi-Fi smart plug, YOUR LOGO on box.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 9.0,
    cbm_per_1000: 0.5,
    sort_order: 16,
    is_active: 1,
  },
  {
    product_name: 'Motion sensor night lights',
    category: 'Tech / Smart Utility',
    short_desc: 'Popular for bedrooms and hallways.',
    why_sells: 'Popular for bedrooms and hallways.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Rechargeable night light, YOUR LOGO on base.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 4.2,
    cbm_per_1000: 0.5,
    sort_order: 17,
    is_active: 1,
  },
  {
    product_name: 'Portable LED desk lamp',
    category: 'Tech / Smart Utility',
    short_desc: 'Useful for study and power outages.',
    why_sells: 'Useful for study and power outages.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Rechargeable desk lamp, YOUR LOGO on stem.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 10.0,
    cbm_per_1000: 1.0,
    sort_order: 18,
    is_active: 1,
  },
  {
    product_name: 'Mini handheld vacuum',
    category: 'Tech / Smart Utility',
    short_desc: 'Car owners like quick clean-ups.',
    why_sells: 'Car owners like quick clean-ups.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Compact handheld vacuum, YOUR LOGO on body.',
    image_url: null,
    fob_low_usd: 8.0,
    fob_high_usd: 15.0,
    cbm_per_1000: 1.0,
    sort_order: 19,
    is_active: 1,
  },
  {
    product_name: 'Bluetooth speaker (mini)',
    category: 'Tech / Smart Utility',
    short_desc: 'Outdoor and social listening culture.',
    why_sells: 'Outdoor and social listening culture.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Mini Bluetooth speaker, YOUR LOGO on grille.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.0,
    sort_order: 20,
    is_active: 1,
  },
  {
    product_name: 'Digital kitchen scale',
    category: 'Tech / Smart Utility',
    short_desc: 'Home bakers and diet tracking.',
    why_sells: 'Home bakers and diet tracking.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Slim digital scale, YOUR LOGO on glass surface.',
    image_url: null,
    fob_low_usd: 2.8,
    fob_high_usd: 6.5,
    cbm_per_1000: 1.0,
    sort_order: 21,
    is_active: 1,
  },
  {
    product_name: 'Rechargeable torch/flashlight',
    category: 'Tech / Smart Utility',
    short_desc: 'Power outages make torches essential.',
    why_sells: 'Power outages make torches essential.',
    regulatory_note: 'Non-regulated (electronics).',
    mockup_prompt: 'Rechargeable torch, YOUR LOGO on side.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 5.0,
    cbm_per_1000: 0.5,
    sort_order: 22,
    is_active: 1,
  },
  {
    product_name: 'Mini tripod + phone mount',
    category: 'Tech / Smart Utility',
    short_desc: 'Content creators need stable shots.',
    why_sells: 'Content creators need stable shots.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Mini tripod with phone mount, YOUR LOGO on box.',
    image_url: null,
    fob_low_usd: 1.5,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.5,
    sort_order: 23,
    is_active: 1,
  },
  {
    product_name: 'Resistance band set',
    category: 'Fitness / Wellness',
    short_desc: 'Affordable home fitness option.',
    why_sells: 'Affordable home fitness option.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Resistance band set, YOUR LOGO on pouch.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 6.0,
    cbm_per_1000: 0.5,
    sort_order: 24,
    is_active: 1,
  },
  {
    product_name: 'Jump rope',
    category: 'Fitness / Wellness',
    short_desc: 'Simple, low-cost cardio tool.',
    why_sells: 'Simple, low-cost cardio tool.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Speed jump rope, YOUR LOGO on handle.',
    image_url: null,
    fob_low_usd: 1.0,
    fob_high_usd: 3.0,
    cbm_per_1000: 0.5,
    sort_order: 25,
    is_active: 1,
  },
  {
    product_name: 'Exercise / yoga mat (PVC)',
    category: 'Fitness / Wellness',
    short_desc: 'Growing fitness trend and visible branding.',
    why_sells: 'Growing fitness trend and visible branding.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Yoga mat with centered YOUR LOGO print.',
    image_url: null,
    fob_low_usd: 5.0,
    fob_high_usd: 9.0,
    cbm_per_1000: 6.0,
    sort_order: 26,
    is_active: 1,
  },
  {
    product_name: 'Massage gun (budget)',
    category: 'Fitness / Wellness',
    short_desc: 'Premium feel at mid price.',
    why_sells: 'Premium feel at mid price.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Budget massage gun, YOUR LOGO on case.',
    image_url: null,
    fob_low_usd: 18.0,
    fob_high_usd: 32.0,
    cbm_per_1000: 1.0,
    sort_order: 27,
    is_active: 1,
  },
  {
    product_name: 'Wrist / ankle weights',
    category: 'Fitness / Wellness',
    short_desc: 'Simple add-on for home workouts.',
    why_sells: 'Simple add-on for home workouts.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Adjustable ankle weights, YOUR LOGO on tag.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.0,
    sort_order: 28,
    is_active: 1,
  },
  {
    product_name: 'Sports water bottle (Tritan)',
    category: 'Fitness / Wellness',
    short_desc: 'Everyday essential, easy branding.',
    why_sells: 'Everyday essential, easy branding.',
    regulatory_note: 'Non-regulated (food-contact plastic).',
    mockup_prompt: 'Tritan bottle with YOUR LOGO print.',
    image_url: null,
    fob_low_usd: 1.2,
    fob_high_usd: 2.5,
    cbm_per_1000: 1.0,
    sort_order: 29,
    is_active: 1,
  },
  {
    product_name: 'Posture corrector',
    category: 'Fitness / Wellness',
    short_desc: 'Strong online demand for desk posture.',
    why_sells: 'Strong online demand for desk posture.',
    regulatory_note: 'Low-regulated (wearable).',
    mockup_prompt: 'Posture corrector with YOUR LOGO on packaging.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 0.5,
    sort_order: 30,
    is_active: 1,
  },
  {
    product_name: 'Magnetic car phone mount',
    category: 'Phone & Computer Accessories',
    short_desc: 'Hands-free use for rideshare and commuters.',
    why_sells: 'Hands-free use for rideshare and commuters.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Magnetic car phone mount on white background with LOGO monogram on packaging.',
    image_url: null,
    fob_low_usd: 1.2,
    fob_high_usd: 3.0,
    cbm_per_1000: 0.4,
    sort_order: 31,
    is_active: 1,
  },
  {
    product_name: 'Phone ring holder / stand',
    category: 'Phone & Computer Accessories',
    short_desc: 'Low-cost impulse accessory with broad appeal.',
    why_sells: 'Low-cost impulse accessory with broad appeal.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Phone ring holder on white background with LOGO monogram.',
    image_url: null,
    fob_low_usd: 0.6,
    fob_high_usd: 1.8,
    cbm_per_1000: 0.25,
    sort_order: 32,
    is_active: 1,
  },
  {
    product_name: '3-in-1 charging cable',
    category: 'Phone & Computer Accessories',
    short_desc: 'Multi-device households need one cable.',
    why_sells: 'Multi-device households need one cable.',
    regulatory_note: 'Low-regulated (electronics accessory).',
    mockup_prompt: '3-in-1 charging cable on white background with LOGO on label.',
    image_url: null,
    fob_low_usd: 0.9,
    fob_high_usd: 2.2,
    cbm_per_1000: 0.35,
    sort_order: 33,
    is_active: 1,
  },
  {
    product_name: 'Apple Watch silicone band',
    category: 'Phone & Computer Accessories',
    short_desc: 'Fashionable upgrades for smartwatch owners.',
    why_sells: 'Fashionable upgrades for smartwatch owners.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Silicone smartwatch band on white background with LOGO on packaging.',
    image_url: null,
    fob_low_usd: 1.2,
    fob_high_usd: 2.8,
    cbm_per_1000: 0.4,
    sort_order: 34,
    is_active: 1,
  },
  {
    product_name: 'Compact Bluetooth keyboard',
    category: 'Phone & Computer Accessories',
    short_desc: 'Remote work and tablets drive demand.',
    why_sells: 'Remote work and tablets drive demand.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Compact Bluetooth keyboard on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 6.0,
    fob_high_usd: 12.0,
    cbm_per_1000: 1.0,
    sort_order: 35,
    is_active: 1,
  },
  {
    product_name: 'Foldable tablet stand',
    category: 'Phone & Computer Accessories',
    short_desc: 'Useful for content viewing and calls.',
    why_sells: 'Useful for content viewing and calls.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Foldable tablet stand on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.6,
    sort_order: 36,
    is_active: 1,
  },
  {
    product_name: 'Earbud cleaning kit',
    category: 'Phone & Computer Accessories',
    short_desc: 'Accessory users want better hygiene.',
    why_sells: 'Accessory users want better hygiene.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Earbud cleaning kit on white background with LOGO on packaging.',
    image_url: null,
    fob_low_usd: 0.8,
    fob_high_usd: 1.6,
    cbm_per_1000: 0.3,
    sort_order: 37,
    is_active: 1,
  },
  {
    product_name: 'USB-C to USB-A adapter pack',
    category: 'Phone & Computer Accessories',
    short_desc: 'Legacy device compatibility remains common.',
    why_sells: 'Legacy device compatibility remains common.',
    regulatory_note: 'Low-regulated (electronics accessory).',
    mockup_prompt: 'USB-C to USB-A adapters on white background with LOGO.',
    image_url: null,
    fob_low_usd: 0.7,
    fob_high_usd: 1.5,
    cbm_per_1000: 0.2,
    sort_order: 38,
    is_active: 1,
  },
  {
    product_name: 'Laptop cleaning kit',
    category: 'Phone & Computer Accessories',
    short_desc: 'Keeps screens and keyboards spotless.',
    why_sells: 'Keeps screens and keyboards spotless.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Laptop cleaning kit on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 1.2,
    fob_high_usd: 2.6,
    cbm_per_1000: 0.45,
    sort_order: 39,
    is_active: 1,
  },
  {
    product_name: 'Screen cleaning spray + cloth set',
    category: 'Phone & Computer Accessories',
    short_desc: 'Simple add-on for device care.',
    why_sells: 'Simple add-on for device care.',
    regulatory_note: 'Low-regulated (non-cosmetic).',
    mockup_prompt: 'Screen cleaning set on white background with LOGO on label.',
    image_url: null,
    fob_low_usd: 0.9,
    fob_high_usd: 1.9,
    cbm_per_1000: 0.4,
    sort_order: 40,
    is_active: 1,
  },
  {
    product_name: 'Mouse pad (PU leather)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Desk upgrades sell well year-round.',
    why_sells: 'Desk upgrades sell well year-round.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'PU leather mouse pad on white background with LOGO emboss.',
    image_url: null,
    fob_low_usd: 1.4,
    fob_high_usd: 3.2,
    cbm_per_1000: 0.7,
    sort_order: 41,
    is_active: 1,
  },
  {
    product_name: 'Cable management clips set',
    category: 'Phone & Computer Accessories',
    short_desc: 'Tidy desks are a constant need.',
    why_sells: 'Tidy desks are a constant need.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Cable management clips on white background with LOGO on packaging.',
    image_url: null,
    fob_low_usd: 0.7,
    fob_high_usd: 1.6,
    cbm_per_1000: 0.3,
    sort_order: 42,
    is_active: 1,
  },
  {
    product_name: 'Phone camera lens kit',
    category: 'Phone & Computer Accessories',
    short_desc: 'Creators want better phone photos.',
    why_sells: 'Creators want better phone photos.',
    regulatory_note: 'Low-regulated (electronics accessory).',
    mockup_prompt: 'Phone camera lens kit on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.5,
    cbm_per_1000: 0.6,
    sort_order: 43,
    is_active: 1,
  },
  {
    product_name: 'Clip-on selfie ring light',
    category: 'Phone & Computer Accessories',
    short_desc: 'Social creators buy frequently.',
    why_sells: 'Social creators buy frequently.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Clip-on selfie ring light on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 5.5,
    cbm_per_1000: 0.8,
    sort_order: 44,
    is_active: 1,
  },
  {
    product_name: 'Mini photo light box',
    category: 'Phone & Computer Accessories',
    short_desc: 'Small sellers need product photos.',
    why_sells: 'Small sellers need product photos.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Mini photo light box on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 8.0,
    fob_high_usd: 15.0,
    cbm_per_1000: 1.5,
    sort_order: 45,
    is_active: 1,
  },
  {
    product_name: 'Wireless charging pad (basic)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Convenience upgrade for modern phones.',
    why_sells: 'Convenience upgrade for modern phones.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Wireless charging pad on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.5,
    cbm_per_1000: 0.9,
    sort_order: 46,
    is_active: 1,
  },
  {
    product_name: 'Compact 5,000mAh power bank',
    category: 'Phone & Computer Accessories',
    short_desc: 'Lightweight backup power is popular.',
    why_sells: 'Lightweight backup power is popular.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Compact power bank on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 7.5,
    cbm_per_1000: 0.9,
    sort_order: 47,
    is_active: 1,
  },
  {
    product_name: 'USB desk fan (mini)',
    category: 'Phone & Computer Accessories',
    short_desc: 'Personal comfort gadget for desks.',
    why_sells: 'Personal comfort gadget for desks.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Mini USB desk fan on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.8,
    fob_high_usd: 5.5,
    cbm_per_1000: 1.0,
    sort_order: 48,
    is_active: 1,
  },
  {
    product_name: 'Laptop privacy webcam cover set',
    category: 'Phone & Computer Accessories',
    short_desc: 'Privacy accessories have steady demand.',
    why_sells: 'Privacy accessories have steady demand.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Webcam covers on white background with LOGO on card.',
    image_url: null,
    fob_low_usd: 0.6,
    fob_high_usd: 1.3,
    cbm_per_1000: 0.2,
    sort_order: 49,
    is_active: 1,
  },
  {
    product_name: 'Portable SSD carry case',
    category: 'Phone & Computer Accessories',
    short_desc: 'Protects drives and accessories.',
    why_sells: 'Protects drives and accessories.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Portable SSD carry case on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.5,
    sort_order: 50,
    is_active: 1,
  },
  {
    product_name: 'Bluetooth tracker tag',
    category: 'Tech / Smart Utility',
    short_desc: 'Helps find keys and bags quickly.',
    why_sells: 'Helps find keys and bags quickly.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Bluetooth tracker tag on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 0.6,
    sort_order: 51,
    is_active: 1,
  },
  {
    product_name: 'Smart door/window sensor',
    category: 'Tech / Smart Utility',
    short_desc: 'Entry alerts for homes and shops.',
    why_sells: 'Entry alerts for homes and shops.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Smart door sensor on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 7.5,
    cbm_per_1000: 0.8,
    sort_order: 52,
    is_active: 1,
  },
  {
    product_name: 'Door stopper alarm',
    category: 'Tech / Smart Utility',
    short_desc: 'Affordable security add-on.',
    why_sells: 'Affordable security add-on.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Door stopper alarm on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.8,
    fob_high_usd: 5.5,
    cbm_per_1000: 0.7,
    sort_order: 53,
    is_active: 1,
  },
  {
    product_name: 'Digital tire pressure gauge',
    category: 'Tech / Smart Utility',
    short_desc: 'Drivers want quick checks.',
    why_sells: 'Drivers want quick checks.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Digital tire pressure gauge on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 5.0,
    cbm_per_1000: 0.6,
    sort_order: 54,
    is_active: 1,
  },
  {
    product_name: 'Rechargeable bike light set',
    category: 'Tech / Smart Utility',
    short_desc: 'Safety accessory for cyclists and riders.',
    why_sells: 'Safety accessory for cyclists and riders.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Rechargeable bike lights on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.0,
    sort_order: 55,
    is_active: 1,
  },
  {
    product_name: 'Bike phone holder',
    category: 'Tech / Smart Utility',
    short_desc: 'Riders need navigation hands-free.',
    why_sells: 'Riders need navigation hands-free.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Bike phone holder on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.2,
    fob_high_usd: 4.5,
    cbm_per_1000: 0.8,
    sort_order: 56,
    is_active: 1,
  },
  {
    product_name: 'Smart plug (dual pack)',
    category: 'Tech / Smart Utility',
    short_desc: 'Simple smart-home upgrade.',
    why_sells: 'Simple smart-home upgrade.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Smart plug pack on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.5,
    fob_high_usd: 9.0,
    cbm_per_1000: 1.0,
    sort_order: 57,
    is_active: 1,
  },
  {
    product_name: 'Digital kitchen timer',
    category: 'Tech / Smart Utility',
    short_desc: 'Home cooks need timing control.',
    why_sells: 'Home cooks need timing control.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Digital timer on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.5,
    fob_high_usd: 3.0,
    cbm_per_1000: 0.4,
    sort_order: 58,
    is_active: 1,
  },
  {
    product_name: 'Laser measuring tape (basic)',
    category: 'Tech / Smart Utility',
    short_desc: 'DIY and contractors need quick measures.',
    why_sells: 'DIY and contractors need quick measures.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Laser measuring tape on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 6.0,
    fob_high_usd: 12.0,
    cbm_per_1000: 1.2,
    sort_order: 59,
    is_active: 1,
  },
  {
    product_name: 'LED strip lights (USB)',
    category: 'Home & Living',
    short_desc: 'Room decor trend among students.',
    why_sells: 'Room decor trend among students.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'USB LED strip lights on white background with LOGO on box.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 7.0,
    cbm_per_1000: 1.2,
    sort_order: 60,
    is_active: 1,
  },
  {
    product_name: 'Closet organizer boxes set',
    category: 'Home & Living',
    short_desc: 'Organizing solutions sell fast.',
    why_sells: 'Organizing solutions sell fast.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Closet organizer boxes on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.4,
    sort_order: 61,
    is_active: 1,
  },
  {
    product_name: 'Drawer dividers set',
    category: 'Home & Living',
    short_desc: 'Simple home organization upgrade.',
    why_sells: 'Simple home organization upgrade.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Drawer dividers on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.5,
    cbm_per_1000: 1.0,
    sort_order: 62,
    is_active: 1,
  },
  {
    product_name: 'Non-slip shelf liner roll',
    category: 'Home & Living',
    short_desc: 'Improves kitchen and wardrobe storage.',
    why_sells: 'Improves kitchen and wardrobe storage.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Shelf liner roll on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 5.0,
    cbm_per_1000: 1.1,
    sort_order: 63,
    is_active: 1,
  },
  {
    product_name: 'Laundry mesh bags (set)',
    category: 'Home & Living',
    short_desc: 'Protects delicates; high repeat need.',
    why_sells: 'Protects delicates; high repeat need.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Laundry mesh bags on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 3.5,
    cbm_per_1000: 0.9,
    sort_order: 64,
    is_active: 1,
  },
  {
    product_name: 'Desk organizer tray set',
    category: 'Home & Living',
    short_desc: 'Clean desks boost productivity.',
    why_sells: 'Clean desks boost productivity.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Desk organizer set on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.2,
    sort_order: 65,
    is_active: 1,
  },
  {
    product_name: 'Document folder organizer',
    category: 'Home & Living',
    short_desc: 'Useful for offices and schools.',
    why_sells: 'Useful for offices and schools.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Document organizer on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.8,
    fob_high_usd: 5.5,
    cbm_per_1000: 1.1,
    sort_order: 66,
    is_active: 1,
  },
  {
    product_name: 'Clip-on book light',
    category: 'Home & Living',
    short_desc: 'Reading accessory with broad appeal.',
    why_sells: 'Reading accessory with broad appeal.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Clip-on book light on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.7,
    sort_order: 67,
    is_active: 1,
  },
  {
    product_name: 'Door draft stopper',
    category: 'Home & Living',
    short_desc: 'Helps keep rooms cooler and quieter.',
    why_sells: 'Helps keep rooms cooler and quieter.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Door draft stopper on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 5.5,
    cbm_per_1000: 1.4,
    sort_order: 68,
    is_active: 1,
  },
  {
    product_name: 'Shoe care brush kit',
    category: 'Home & Living',
    short_desc: 'Popular with sneaker users.',
    why_sells: 'Popular with sneaker users.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Shoe care brush kit on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 3.8,
    cbm_per_1000: 0.9,
    sort_order: 69,
    is_active: 1,
  },
  {
    product_name: 'Packing cubes set',
    category: 'Travel & Outdoor',
    short_desc: 'Travelers want neat luggage.',
    why_sells: 'Travelers want neat luggage.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Packing cubes on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 7.0,
    cbm_per_1000: 1.5,
    sort_order: 70,
    is_active: 1,
  },
  {
    product_name: 'Luggage scale (digital)',
    category: 'Travel & Outdoor',
    short_desc: 'Avoids excess baggage fees.',
    why_sells: 'Avoids excess baggage fees.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Digital luggage scale on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 6.5,
    cbm_per_1000: 0.7,
    sort_order: 71,
    is_active: 1,
  },
  {
    product_name: 'Travel neck pillow (memory foam)',
    category: 'Travel & Outdoor',
    short_desc: 'Comfort item for long trips.',
    why_sells: 'Comfort item for long trips.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Travel neck pillow on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.5,
    fob_high_usd: 9.0,
    cbm_per_1000: 1.8,
    sort_order: 72,
    is_active: 1,
  },
  {
    product_name: 'Compact umbrella (windproof)',
    category: 'Travel & Outdoor',
    short_desc: 'Everyday weather accessory.',
    why_sells: 'Everyday weather accessory.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Compact umbrella on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 7.0,
    cbm_per_1000: 1.6,
    sort_order: 73,
    is_active: 1,
  },
  {
    product_name: 'Reusable silicone travel bottles set',
    category: 'Travel & Outdoor',
    short_desc: 'Popular for carry-on travel.',
    why_sells: 'Popular for carry-on travel.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Silicone travel bottles on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.8,
    sort_order: 74,
    is_active: 1,
  },
  {
    product_name: 'Electronics travel organizer pouch',
    category: 'Travel & Outdoor',
    short_desc: 'Keeps gadgets and cables tidy.',
    why_sells: 'Keeps gadgets and cables tidy.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Travel organizer pouch on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.1,
    sort_order: 75,
    is_active: 1,
  },
  {
    product_name: 'RFID blocking card holder',
    category: 'Travel & Outdoor',
    short_desc: 'Small security accessory for travel.',
    why_sells: 'Small security accessory for travel.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'RFID card holder on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.5,
    cbm_per_1000: 0.4,
    sort_order: 76,
    is_active: 1,
  },
  {
    product_name: 'Anti-theft backpack lock',
    category: 'Travel & Outdoor',
    short_desc: 'Simple security add-on for bags.',
    why_sells: 'Simple security add-on for bags.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Backpack lock on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.5,
    fob_high_usd: 3.5,
    cbm_per_1000: 0.4,
    sort_order: 77,
    is_active: 1,
  },
  {
    product_name: 'Lightweight duffel bag',
    category: 'Travel & Outdoor',
    short_desc: 'Gym and travel use cases.',
    why_sells: 'Gym and travel use cases.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Duffel bag on white background with LOGO.',
    image_url: null,
    fob_low_usd: 6.0,
    fob_high_usd: 12.0,
    cbm_per_1000: 2.5,
    sort_order: 78,
    is_active: 1,
  },
  {
    product_name: 'Car seat organizer',
    category: 'Travel & Outdoor',
    short_desc: 'Keeps cars tidy for families.',
    why_sells: 'Keeps cars tidy for families.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Car seat organizer on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 2.0,
    sort_order: 79,
    is_active: 1,
  },
  {
    product_name: 'Car trash bin (mini)',
    category: 'Travel & Outdoor',
    short_desc: 'Small car accessory with daily use.',
    why_sells: 'Small car accessory with daily use.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Car trash bin on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 1.0,
    sort_order: 80,
    is_active: 1,
  },
  {
    product_name: 'Foam roller',
    category: 'Fitness / Wellness',
    short_desc: 'Recovery tools are in steady demand.',
    why_sells: 'Recovery tools are in steady demand.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Foam roller on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.5,
    fob_high_usd: 9.0,
    cbm_per_1000: 2.0,
    sort_order: 81,
    is_active: 1,
  },
  {
    product_name: 'Yoga blocks (pair)',
    category: 'Fitness / Wellness',
    short_desc: 'Beginner yoga accessories.',
    why_sells: 'Beginner yoga accessories.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Yoga blocks on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.5,
    fob_high_usd: 7.0,
    cbm_per_1000: 1.6,
    sort_order: 82,
    is_active: 1,
  },
  {
    product_name: 'Pilates ring',
    category: 'Fitness / Wellness',
    short_desc: 'Lightweight fitness accessory.',
    why_sells: 'Lightweight fitness accessory.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Pilates ring on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.0,
    sort_order: 83,
    is_active: 1,
  },
  {
    product_name: 'Hand grip strengthener set',
    category: 'Fitness / Wellness',
    short_desc: 'Affordable fitness gadget.',
    why_sells: 'Affordable fitness gadget.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Hand grip strengthener on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.8,
    sort_order: 84,
    is_active: 1,
  },
  {
    product_name: 'Ankle/hand weights (pair)',
    category: 'Fitness / Wellness',
    short_desc: 'Popular for home workouts.',
    why_sells: 'Popular for home workouts.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Ankle weights on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.8,
    sort_order: 85,
    is_active: 1,
  },
  {
    product_name: 'Yoga strap',
    category: 'Fitness / Wellness',
    short_desc: 'Low-cost yoga add-on.',
    why_sells: 'Low-cost yoga add-on.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Yoga strap on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.5,
    fob_high_usd: 3.0,
    cbm_per_1000: 0.7,
    sort_order: 86,
    is_active: 1,
  },
  {
    product_name: 'Exercise slider discs',
    category: 'Fitness / Wellness',
    short_desc: 'Compact home workout tool.',
    why_sells: 'Compact home workout tool.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Exercise sliders on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 3.5,
    cbm_per_1000: 0.8,
    sort_order: 87,
    is_active: 1,
  },
  {
    product_name: 'Skipping rope with counter',
    category: 'Fitness / Wellness',
    short_desc: 'Adds tracking to cardio.',
    why_sells: 'Adds tracking to cardio.',
    regulatory_note: 'Low-regulated (electronics).',
    mockup_prompt: 'Skipping rope with counter on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 5.0,
    cbm_per_1000: 0.9,
    sort_order: 88,
    is_active: 1,
  },
  {
    product_name: 'Sports towel (quick dry)',
    category: 'Fitness / Wellness',
    short_desc: 'Gym essential with repeat demand.',
    why_sells: 'Gym essential with repeat demand.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Quick dry sports towel on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 3.5,
    cbm_per_1000: 1.0,
    sort_order: 89,
    is_active: 1,
  },
  {
    product_name: 'Gym belt (basic)',
    category: 'Fitness / Wellness',
    short_desc: 'Support gear for weight training.',
    why_sells: 'Support gear for weight training.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Gym belt on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.6,
    sort_order: 90,
    is_active: 1,
  },
  {
    product_name: 'Laptop stand (foldable plastic)',
    category: 'Office & Productivity',
    short_desc: 'Budget alternative to aluminum stands.',
    why_sells: 'Budget alternative to aluminum stands.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Foldable laptop stand on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.8,
    fob_high_usd: 5.5,
    cbm_per_1000: 1.1,
    sort_order: 91,
    is_active: 1,
  },
  {
    product_name: 'Desk mat (large)',
    category: 'Office & Productivity',
    short_desc: 'Premium desk look and feel.',
    why_sells: 'Premium desk look and feel.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Large desk mat on white background with LOGO.',
    image_url: null,
    fob_low_usd: 4.0,
    fob_high_usd: 8.0,
    cbm_per_1000: 1.8,
    sort_order: 92,
    is_active: 1,
  },
  {
    product_name: 'Cable tie roll (Velcro)',
    category: 'Office & Productivity',
    short_desc: 'Universal use for cables.',
    why_sells: 'Universal use for cables.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Velcro cable ties on white background with LOGO.',
    image_url: null,
    fob_low_usd: 0.9,
    fob_high_usd: 2.0,
    cbm_per_1000: 0.4,
    sort_order: 93,
    is_active: 1,
  },
  {
    product_name: 'Mouse wrist rest',
    category: 'Office & Productivity',
    short_desc: 'Comfort accessory for desk users.',
    why_sells: 'Comfort accessory for desk users.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Mouse wrist rest on white background with LOGO.',
    image_url: null,
    fob_low_usd: 1.8,
    fob_high_usd: 3.5,
    cbm_per_1000: 0.9,
    sort_order: 94,
    is_active: 1,
  },
  {
    product_name: 'Laptop sleeve (neoprene)',
    category: 'Office & Productivity',
    short_desc: 'Protects laptops on the go.',
    why_sells: 'Protects laptops on the go.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Neoprene laptop sleeve on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 1.4,
    sort_order: 95,
    is_active: 1,
  },
  {
    product_name: 'Headphone stand',
    category: 'Office & Productivity',
    short_desc: 'Keeps desk tidy and premium.',
    why_sells: 'Keeps desk tidy and premium.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Headphone stand on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.5,
    fob_high_usd: 5.0,
    cbm_per_1000: 1.0,
    sort_order: 96,
    is_active: 1,
  },
  {
    product_name: 'Key organizer (compact)',
    category: 'Lifestyle & Personal',
    short_desc: 'Keeps keys quiet and tidy.',
    why_sells: 'Keeps keys quiet and tidy.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Key organizer on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.5,
    sort_order: 97,
    is_active: 1,
  },
  {
    product_name: 'Minimalist wallet',
    category: 'Lifestyle & Personal',
    short_desc: 'Slim wallets are popular.',
    why_sells: 'Slim wallets are popular.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Minimalist wallet on white background with LOGO.',
    image_url: null,
    fob_low_usd: 3.0,
    fob_high_usd: 6.0,
    cbm_per_1000: 0.6,
    sort_order: 98,
    is_active: 1,
  },
  {
    product_name: 'Phone grip pop socket',
    category: 'Lifestyle & Personal',
    short_desc: 'Low-cost accessory with mass appeal.',
    why_sells: 'Low-cost accessory with mass appeal.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Phone grip accessory on white background with LOGO.',
    image_url: null,
    fob_low_usd: 0.7,
    fob_high_usd: 1.6,
    cbm_per_1000: 0.25,
    sort_order: 99,
    is_active: 1,
  },
  {
    product_name: 'Reusable water bottle sling',
    category: 'Lifestyle & Personal',
    short_desc: 'Hands-free carry for bottles.',
    why_sells: 'Hands-free carry for bottles.',
    regulatory_note: 'Non-regulated.',
    mockup_prompt: 'Water bottle sling on white background with LOGO.',
    image_url: null,
    fob_low_usd: 2.0,
    fob_high_usd: 4.0,
    cbm_per_1000: 0.9,
    sort_order: 100,
    is_active: 1,
  },
]

function loadWhiteLabelSeed(): WhiteLabelProductSeed[] {
  const jsonPath = path.join(process.cwd(), "data", "white-label-products.json");
  try {
    if (!fs.existsSync(jsonPath)) return WHITE_LABEL_PRODUCT_SEED;
    const raw = fs.readFileSync(jsonPath, "utf8").trim();
    if (!raw) return WHITE_LABEL_PRODUCT_SEED;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed as WhiteLabelProductSeed[];
  } catch {
    return WHITE_LABEL_PRODUCT_SEED;
  }
  return WHITE_LABEL_PRODUCT_SEED;
}


function toNumber(val: any) {
  if (val === null || val === undefined || val === "") return null;
  const n = Number(val);
  return Number.isFinite(n) ? n : null;
}

function slugify(value: string) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
}

let didEnsureTable = false;
let didSeedProducts = false;
let didEnsureViews = false;
let didBackfillSlugs = false;

export function computeLandedRange(input: {
  fob_low_usd: number | null | string | undefined;
  fob_high_usd: number | null | string | undefined;
  cbm_per_1000: number | null | string | undefined;
  fx_rate_ngn?: number;
  cbm_rate_ngn?: number;
  markup_percent?: number;
}) {
  const fx = toNumber(input.fx_rate_ngn ?? WHITE_LABEL_PRICING_DEFAULTS.fx_rate_ngn) ?? 0;
  const cbmRate = toNumber(input.cbm_rate_ngn ?? WHITE_LABEL_PRICING_DEFAULTS.cbm_rate_ngn) ?? 0;
  const markup = toNumber(input.markup_percent ?? WHITE_LABEL_PRICING_DEFAULTS.markup_percent) ?? 0;

  const fobLow = toNumber(input.fob_low_usd);
  const fobHigh = toNumber(input.fob_high_usd);
  const cbm = toNumber(input.cbm_per_1000);

  if (fobLow === null || fobHigh === null || cbm === null) {
    return {
      freight_per_unit_ngn: null,
      landed_ngn_per_unit_low: null,
      landed_ngn_per_unit_high: null,
      landed_ngn_total_1000_low: null,
      landed_ngn_total_1000_high: null,
    };
  }

  const freightPerUnit = (cbm * cbmRate) / 1000;
  const landedLowRaw = (fobLow * fx + freightPerUnit) * (1 + markup);
  const landedLow = landedLowRaw * 0.5;
  const landedHigh = (fobHigh * fx + freightPerUnit) * (1 + markup);

  return {
    freight_per_unit_ngn: freightPerUnit,
    landed_ngn_per_unit_low: landedLow,
    landed_ngn_per_unit_high: landedHigh,
    landed_ngn_total_1000_low: landedLow * 1000,
    landed_ngn_total_1000_high: landedHigh * 1000,
  };
}

export async function ensureWhiteLabelProductsTable(conn: PoolConnection) {
  await conn.query(`
    CREATE TABLE IF NOT EXISTS linescout_white_label_products (
      id INT AUTO_INCREMENT PRIMARY KEY,
      product_name VARCHAR(255) NOT NULL,
      category VARCHAR(255) NOT NULL,
      short_desc TEXT NULL,
      why_sells TEXT NULL,
      regulatory_note TEXT NULL,
      mockup_prompt TEXT NULL,
      image_url VARCHAR(500) NULL,
      slug VARCHAR(255) NULL,
      seo_title VARCHAR(255) NULL,
      seo_description VARCHAR(500) NULL,
      business_summary TEXT NULL,
      market_notes TEXT NULL,
      white_label_angle TEXT NULL,
      fob_low_usd DECIMAL(10,2) NULL,
      fob_high_usd DECIMAL(10,2) NULL,
      cbm_per_1000 DECIMAL(10,4) NULL,
      size_template VARCHAR(32) NULL,
      volumetric_kg_per_1000 DECIMAL(10,2) NULL,
      landed_gbp_sea_per_unit_low DECIMAL(10,4) NULL,
      landed_gbp_sea_per_unit_high DECIMAL(10,4) NULL,
      landed_gbp_sea_total_1000_low DECIMAL(12,2) NULL,
      landed_gbp_sea_total_1000_high DECIMAL(12,2) NULL,
      landed_cad_sea_per_unit_low DECIMAL(10,4) NULL,
      landed_cad_sea_per_unit_high DECIMAL(10,4) NULL,
      landed_cad_sea_total_1000_low DECIMAL(12,2) NULL,
      landed_cad_sea_total_1000_high DECIMAL(12,2) NULL,
      is_active TINYINT NOT NULL DEFAULT 1,
      sort_order INT NOT NULL DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  await ensureColumn(conn, "linescout_white_label_products", "slug", "VARCHAR(255) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "seo_title", "VARCHAR(255) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "seo_description", "VARCHAR(500) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "business_summary", "TEXT NULL");
  await ensureColumn(conn, "linescout_white_label_products", "market_notes", "TEXT NULL");
  await ensureColumn(conn, "linescout_white_label_products", "white_label_angle", "TEXT NULL");
  await ensureColumn(conn, "linescout_white_label_products", "size_template", "VARCHAR(32) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "volumetric_kg_per_1000", "DECIMAL(10,2) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_gbp_sea_per_unit_low", "DECIMAL(10,4) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_gbp_sea_per_unit_high", "DECIMAL(10,4) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_gbp_sea_total_1000_low", "DECIMAL(12,2) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_gbp_sea_total_1000_high", "DECIMAL(12,2) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_cad_sea_per_unit_low", "DECIMAL(10,4) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_cad_sea_per_unit_high", "DECIMAL(10,4) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_cad_sea_total_1000_low", "DECIMAL(12,2) NULL");
  await ensureColumn(conn, "linescout_white_label_products", "landed_cad_sea_total_1000_high", "DECIMAL(12,2) NULL");

  await conn.query(
    `CREATE INDEX IF NOT EXISTS idx_white_label_slug ON linescout_white_label_products (slug)`
  ).catch(() => {});
}

export async function ensureWhiteLabelProductsReady(conn: PoolConnection) {
  if (!didEnsureTable) {
    await ensureWhiteLabelProductsTable(conn);
    didEnsureTable = true;
  }
  if (!didEnsureViews) {
    await ensureWhiteLabelViewsTable(conn);
    didEnsureViews = true;
  }
  if (!didBackfillSlugs) {
    await backfillWhiteLabelSlugs(conn);
    didBackfillSlugs = true;
  }

  if (process.env.AUTO_SEED_WHITE_LABEL === "1" && !didSeedProducts) {
    await seedWhiteLabelProducts(conn);
    didSeedProducts = true;
  }
}

async function backfillWhiteLabelSlugs(conn: PoolConnection) {
  const [rows]: any = await conn.query(
    `
    SELECT id, product_name
    FROM linescout_white_label_products
    WHERE COALESCE(slug, '') = ''
    LIMIT 5000
    `
  );
  if (!rows?.length) return;

  for (const row of rows) {
    const slug = slugify(String(row.product_name || ""));
    if (!slug) continue;
    await conn.query(
      `UPDATE linescout_white_label_products SET slug = ? WHERE id = ?`,
      [slug, row.id]
    );
  }
}

export async function ensureWhiteLabelViewsTable(conn: PoolConnection) {
  await conn.query(`
    CREATE TABLE IF NOT EXISTS linescout_white_label_views (
      id INT AUTO_INCREMENT PRIMARY KEY,
      product_id INT NOT NULL,
      viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_white_label_views_product (product_id),
      INDEX idx_white_label_views_time (viewed_at)
    )
  `);
}

export async function seedWhiteLabelProducts(conn: PoolConnection) {
  const [rows]: any = await conn.query(
    `SELECT product_name, category FROM linescout_white_label_products`
  );

  const existing = new Set(
    (rows || []).map((r: any) => `${String(r.product_name || '').toLowerCase()}||${String(r.category || '').toLowerCase()}`)
  );

  const seed = loadWhiteLabelSeed();
  const toInsert = seed.filter((p) => {
    const key = `${p.product_name.toLowerCase()}||${p.category.toLowerCase()}`;
    return !existing.has(key);
  });

  if (!toInsert.length) return;

  const chunkSize = 200;
  for (let i = 0; i < toInsert.length; i += chunkSize) {
    const chunk = toInsert.slice(i, i + chunkSize);
    const values = chunk.map((p) => [
      p.product_name,
      p.category,
      p.short_desc,
      p.why_sells,
      p.regulatory_note,
      p.mockup_prompt,
      p.image_url,
      p.slug || slugify(p.product_name),
      p.seo_title || null,
      p.seo_description || null,
      p.business_summary || null,
      p.market_notes || null,
      p.white_label_angle || null,
      p.fob_low_usd,
      p.fob_high_usd,
      p.cbm_per_1000,
      p.is_active,
      p.sort_order,
    ]);

    await conn.query(
      `
      INSERT INTO linescout_white_label_products
        (product_name, category, short_desc, why_sells, regulatory_note, mockup_prompt, image_url,
         slug, seo_title, seo_description, business_summary, market_notes, white_label_angle,
         fob_low_usd, fob_high_usd, cbm_per_1000, is_active, sort_order)
      VALUES ?
      `,
      [values]
    );
  }
}

async function ensureColumn(conn: PoolConnection, table: string, column: string, definition: string) {
  const [rows]: any = await conn.query(
    `SELECT 1
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = ?
       AND COLUMN_NAME = ?
     LIMIT 1`,
    [table, column]
  );
  if (rows?.length) return;
  await conn.query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
}
