'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import * as Dialog from '@radix-ui/react-dialog';
import {Calculator,X} from 'lucide-react';
import {CALCULATION_VERSION,validateCalculation,type CalculationRecord,type CalculationInput} from '@/lib/calculation-records';
import {calculationRequest,CalculationRequestError,requestKey,saveCalculation} from '@/lib/calculation-account-client';
import styles from '@/components/calculations/CalculationAccount.module.css';
type ImportItem={key:string;input:CalculationInput};
export default function MyCalculations(){
 const router=useRouter();const [items,setItems]=useState<CalculationRecord[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[platform,setPlatform]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[deleting,setDeleting]=useState<CalculationRecord|null>(null),[imports,setImports]=useState<ImportItem[]>([]),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setPage(1);},250);return ()=>clearTimeout(timer);},[search]);
 useEffect(()=>{let active=true;setLoading(true);setError('');calculationRequest('?'+new URLSearchParams({page:String(page),platform,q:query})).then(data=>{if(active){setItems(data.calculations);setTotal(data.total);}}).catch(e=>{if(!active)return;if(e instanceof CalculationRequestError&&e.status===401)router.replace('/sign-in?next=%2Fcalculations');else setError(e.message);}).finally(()=>{if(active)setLoading(false);});return ()=>{active=false;};},[page,platform,query,reload,router]);
 function findImports(){const found:ImportItem[]=[];try{for(const p of ['amazon','tiktok'] as const){const values=JSON.parse(localStorage.getItem(`linescout-${p}-calculations-v1`)||'[]');if(!Array.isArray(values))continue;for(const item of values.slice(0,5)){try{if(typeof item.id!=='string')continue;const input=validateCalculation({...item,platform:p,modelVersion:CALCULATION_VERSION});found.push({key:`browser:${p}:${item.id}`.slice(0,100),input});}catch{}}}setImports(found);setSelected(found.map(x=>x.key));setNotice(found.length?'Choose which browser calculations to copy to your account. The originals will stay on this device.':'No valid browser-saved calculations were found on this device.');}catch{setError('Your browser storage is unavailable. Try the browser where you saved your calculations.');}}
 async function importSelected(){setBusy('import');setError('');let count=0;try{for(const item of imports.filter(i=>selected.includes(i.key))){await saveCalculation(item.input,item.key);count++;}setNotice(`${count} calculation${count===1?'':'s'} available in your account. Previously imported copies were not duplicated.`);setImports([]);setSelected([]);setPage(1);setReload(v=>v+1);}catch(e){setError(`${count} saved before the import stopped. ${(e as Error).message} You can safely try again; originals remain on this device.`);setReload(v=>v+1);}finally{setBusy('');}}
 async function duplicate(item:CalculationRecord){setBusy(item.id);setError('');try{if(item.modelVersion!==CALCULATION_VERSION){router.push('/amazon-profit-calculator?saved='+item.id);return;}await saveCalculation({...item,name:(item.name+' (copy)').slice(0,160)},requestKey());setNotice('A separate copy has been saved.');setPage(1);setReload(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function download(item:CalculationRecord){setBusy(item.id);setError('');try{const response=await fetch('/api/calculations?'+new URLSearchParams({id:item.id,format:'csv'}),{credentials:'include',cache:'no-store'});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Could not download this calculation. Please try again.');}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='linescout-'+item.platform+'-'+item.id+'.csv';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function remove(){if(!deleting)return;setBusy('delete');setError('');try{await calculationRequest('',{method:'DELETE',body:JSON.stringify({id:deleting.id})});setDeleting(null);setNotice('Calculation deleted from your account.');if(items.length===1&&page>1)setPage(p=>p-1);else setReload(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <div className={styles.page}><header className={styles.heading}><div><h1>My calculations</h1><p>Your product ideas and estimated profits, saved privately to your account.</p></div><Link className={`${styles.button} ${styles.primary}`} href="/amazon-profit-calculator">New calculation</Link></header>
 <div className={styles.filters}><input aria-label="Search calculations" placeholder="Search by calculation name" maxLength={160} value={search} onChange={e=>setSearch(e.target.value)}/>{[['','All'],['amazon','Amazon'],['tiktok','TikTok Shop']].map(([value,label])=><button key={value} type="button" aria-pressed={platform===value} onClick={()=>{setPlatform(value);setPage(1);}}>{label}</button>)}</div>
 {error&&<p role="alert" className={styles.error}>{error} <button type="button" onClick={()=>setReload(v=>v+1)}>Try again</button></p>}{notice&&<p role="status" className={styles.success}>{notice}</p>}
 {loading?<div className={styles.empty} role="status">Loading your calculations…</div>:!error&&items.length===0?<section className={styles.empty}><Calculator size={36}/><h2>{query||platform?'No matching calculations':'Your next product idea starts here.'}</h2><p>{query||platform?'Try another name or platform.':'Use the free Amazon or TikTok Shop calculator, then save your figures here to compare, edit and revisit them.'}</p><Link className={`${styles.button} ${styles.primary}`} href="/amazon-profit-calculator">Open the calculator</Link></section>:<div className={styles.grid}>{items.map(item=><article key={item.id} className={styles.card}><small>{item.platform==='amazon'?'Amazon':'TikTok Shop'} · {item.market==='GB'?'United Kingdom':item.market==='CA'?'Canada':'United States'} · {item.currency}</small><h2>{item.name}</h2><p>Estimated profit per product<strong>{new Intl.NumberFormat('en-GB',{style:'currency',currency:item.currency}).format(item.result.profit)}</strong>{item.result.profitMargin.toFixed(1)}% estimated profit margin</p><p>Selling price: {new Intl.NumberFormat('en-GB',{style:'currency',currency:item.currency}).format(item.result.price)}</p><p>Updated {new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(new Date(item.updatedAt))}</p>{item.modelVersion!==CALCULATION_VERSION&&<p className={styles.warning}>Open to review the updated calculation method.</p>}<div className={styles.actions}><Link href={'/amazon-profit-calculator?saved='+item.id}>Open and edit</Link><button type="button" disabled={!!busy} onClick={()=>download(item)}>Download CSV</button><button type="button" disabled={!!busy} onClick={()=>duplicate(item)}>Duplicate</button><button type="button" disabled={!!busy} onClick={()=>{setError('');setDeleting(item);}}>Delete</button></div></article>)}</div>}
 {total>20&&<nav className={styles.pagination} aria-label="Calculation pages"><button disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.ceil(total/20)}</span><button disabled={loading||page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}
 <details className={styles.import}><summary>Previously saved calculations on this device?</summary><p>Copy your old browser saves to your account. They will stay private, and the originals will not be removed.</p><button type="button" disabled={!!busy} onClick={findImports}>Find browser saves</button>{imports.map(item=><label key={item.key}><input type="checkbox" checked={selected.includes(item.key)} disabled={!!busy} onChange={e=>setSelected(values=>e.target.checked?[...values,item.key]:values.filter(k=>k!==item.key))}/><span>{item.input.name} · {item.input.platform==='amazon'?'Amazon':'TikTok Shop'} · {item.input.market}</span></label>)}{imports.length>0&&<button type="button" disabled={!!busy||!selected.length} onClick={importSelected}>{busy==='import'?'Importing…':'Import selected calculations'}</button>}</details>
 <Dialog.Root open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><Dialog.Portal><Dialog.Overlay className={styles.overlay}/><Dialog.Content className={styles.dialog}><Dialog.Close disabled={!!busy} className={styles.close} aria-label="Close"><X size={20}/></Dialog.Close><Dialog.Title>Delete this calculation?</Dialog.Title><Dialog.Description>“{deleting?.name}” will be removed from your account. This cannot be undone.</Dialog.Description>{error&&<p role="alert" className={styles.error}>{error}</p>}<div className={styles.actions}><button disabled={!!busy} onClick={()=>setDeleting(null)}>Keep calculation</button><button disabled={!!busy} onClick={remove}>{busy==='delete'?'Deleting…':'Delete calculation'}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
